#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 195830-web-01 3.85.175.167:80 check\n\tserver 195830-web-02 34.239.107.183:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
