#!/usr/bin/env bash
# Requirements:
# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database.
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
