#!/usr/bin/env bash
# The script display Best School 10times but
#for the 9th iteration,displays Best school and then Hi in a new line.

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if ((i == 9))
	then
		echo "Hi"
	fi
	((i++))
done
