#!/usr/bin/env bash
# Requirements:
# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
# make sure to try your script by passing different users

if [ $# -eq 1 ]
then
    sudo -u "$1" whoami
else
    echo "Usage: 0-iamsomeonelese USER"
fi
