#!/usr/bin/env bash
# A bash script that reload a gunicorn in a graceful way.

# Getting the PID of the gunicorn process.
gunicorn_pid=$(pgrep gunicorn | head -n 1)

#use the gunicorn_pid to generate the worker pid
worker_pid=$(pgrep -P gunicorn_pid)

# send a SIGHUP signal to restart the gunicorn for each worker_pid
for worker in "${worker_pid[@]}"
do
    kill -SIGHUP "$worker"
done
