#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client,
# let’s configure it to our needs so that you can connect to a server without
# typing a password. Share your SSH client configuration in your answer file.
#  Requirements:
# Your SSH client configuration must be configured to use the private key ~/.ssh/school
# Your SSH client configuration must be configured to refuse to authenticate using a password

Include /etc/ssh/ssh_config.d/*.conf
 20
 21 Host *
 22 #   ForwardAgent no
 23 #   ForwardX11 no
 24 #   ForwardX11Trusted yes
 25    PasswordAuthentication yes
 26 #   HostbasedAuthentication no
 27 #   GSSAPIAuthentication no
 28 #   GSSAPIDelegateCredentials no
 29 #   GSSAPIKeyExchange no
 30 #   GSSAPITrustDNS no
 31 #   BatchMode no
 32 #   CheckHostIP yes
 33 #   AddressFamily any
 34 #   ConnectTimeout 0
 35 #   StrictHostKeyChecking ask
 36    IdentityFile ~/.ssh/school
 37 #   IdentityFile ~/.ssh/id_dsa
 38 #   IdentityFile ~/.ssh/id_ecdsa
 39 #   IdentityFile ~/.ssh/id_ed25519
 40 #   Port 22
 41 #   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
 42 #   MACs hmac-md5,hmac-sha1,umac-64@openssh.com
 43 #   EscapeChar ~
 44 #   Tunnel no
 45 #   TunnelDevice any:any
 46 #   PermitLocalCommand no
 47 #   VisualHostKey no
 48 #   ProxyCommand ssh -q -W %h:%p gateway.example.com
 49 #   RekeyLimit 1G 1h
 50     SendEnv LANG LC_*
 51     HashKnownHosts yes
 52     GSSAPIAuthentication yes
